server:
  servlet:
    context-path: /
  port: 8081
  compression:
    mime-types:
      - application/json

spring:
  application:
    name: channel-service
  main:
    allow-bean-definition-overriding: true

#Remove this feature to enable database connections
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: false


## Enabling database connection
datasource:
  url: jdbc:mysql://localhost:<port>/<db>
  username: package
  password: package
  continue-on-error: true
jpa:
  open-in-view: false
  show-sql: true
  format-sql: true
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.mysql
  properties:
    hibernate:
      jdbc:
        batch_size: 50

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/subscription
    username: root
    password: package
    driver-class-name: com.mysql.jdbc.Driver
    schemas: package

## Enabling rabbitmq
# rabbitmq:
#   host: 127.0.0.1
#   port: 5672
#   username: package
#   password: package
#   cache:
#     connection:
#       mode: CONNECTION
#     channel:
#       size: 50
#     checkout-timeout: 10000
